PUT http://localhost:8477/users/
Content-Type: application/json

{
  "Name" :  "tobias",
  "Email":  "tobias.leichtfried@sz-ybbs.ac.at",
  "Password":  "geheim"
}
###
PUT http://localhost:8477/users/
Content-Type: application/json

{
  "Name" :  "test_user",
  "Email":  "test_user@gmail.com",
  "Password":  "zu"
}